### ISSUE TITLE
Feature Request - Ionicon auto-import

### ISSUE THREAD

**Issue by i13-ctflora** [ionic-team/vscode-ionic#178]
Much like the extension auto-imports ionic components when added to the template, it would be great if we could also get ionicons auto-imported.

**Comment by EvanBelcher** [comment]
This change is now breaking my non-ionic projects. Whenever I save my angular html files, it is auto-adding an import to addIcons from ionicons, which then inevitably causes an error because I don't even have ionicons installed. I had to completely disable the extension. Maybe I'm incorrect, but I feel that extensions like these should be made in a way that are non-obtrusive for things they don't apply to.

**Comment by dtarnawsky** [comment]
Hey @EvanBelcher , this should now be patched up. Let me know if you have any problems with v1.93.4
