### ISSUE TITLE
 Unexpected Import of addIcons from ionicons When Formatting HTML Templates with Prettier

### ISSUE THREAD

**Issue by raulgonzaleztahiche** [ionic-team/vscode-ionic#187]
Description:

While working with Angular 18, I’ve encountered an issue where Prettier automatically adds an import statement for addIcons from ionicons in the TypeScript file of a component after formatting its associated HTML template.

Steps to Reproduce:

	1.	Use Angular 18 and Prettier for code formatting.
	2.	Create a new component with an HTML template.
	3.	Edit the HTML template in the component.
	4.	Run Prettier to format the template.
	5.	After formatting, an unwanted import statement import { addIcons } from "ionicons"; is automatically added to the component’s TypeScript file.

Expected Behavior:

Prettier should format the HTML template without modifying the TypeScript file or adding any unnecessary import statements.

Actual Behavior:

Prettier automatically adds the following import to the TypeScript file of the component:

import { addIcons } from "ionicons";

Temporary Workaround:

Disabling the Ionic extension prevents this issue from occurring.

Environment:

	•	Angular version: 18
	•	Prettier version: 3.3.3
	•	Operating System: macOS Sonoma

Additional Context:

This issue only appears after formatting an HTML template and does not seem to be triggered by any changes made directly in the TypeScript file.

**Comment by lollomrt** [comment]
I'm experiencing the problem too. 
When saving the html file, both import { addIcons } from "ionicons" and also the icons that are detected in the html are imported.

Furthermore, the addIcons() function is automatically generated in the constructor with duplicate icons. e.g.: `addIcons({chatbubbleEllipsesOutline,mapOutline,reorderTwo,print,print,chatbubbleEllipsesOutline,mapOutline,pencil,reorderTwo,print}); }`

I confirm that the problem is eliminated by disabling the extension.

- Angular Version: 17.3.9
- Operating System: macOS Sonoma

**Comment by dtarnawsky** [comment]
Hey Raul & Lorenzo, thanks for reporting the issue. It should now be fixed in 1.93.3 which fixes the issue of adding imports for ionicons even when none are used in the template, and also fixes the issue of duplicate icons being added to the constructor's addIcons method.
