### ISSUE TITLE
Launch Web Dev changed behaviour

### ISSUE THREAD

**Issue by rgilsimoes** [ionic-team/vscode-ionic#190]
The launch Web Development server has changed behaviour:

Previously v.1.92.1:
![image](https://github.com/user-attachments/assets/c29d955f-9ee6-4f94-bb97-62ce12cb2257)

Current v.1.93.4: 
![image](https://github.com/user-attachments/assets/b8d22629-8f40-4c6c-a307-89143f2c1ff7)

Issues:

- No localhost binding
- No remote logging service

**Comment by dtarnawsky** [comment]
Thanks Ricardo,

Yes, latest update is specific with the IP address it uses because it needed to be to support Live Reload with the Capacitor CLI.

It looks like your mac has 2 IP addresses: 192.168.1.85 and 192.168.1.96 and would likely have asked you which address you wanted to use?

I'll see if I can put an option in to allow you to select all addresses (or perhaps default to that when live reload is not used).

**Comment by dtarnawsky** [comment]
Hey Ricardo,

v1.94 is now out. I worked over the weekend on this and it should be working by default with localhost and other external addresses, using external Ip Addresses if you use live reload or use the Nexus Browser option.

Let me know if you see any issues.

**Comment by rgilsimoes** [comment]
It's ok now!
