### ISSUE TITLE
Unable to disable icon auto import

### ISSUE THREAD

**Issue by MattOnyx** [ionic-team/vscode-ionic#195]
I said yes when I got prompted to try the new auto import for icons, but now it's deleting icons that I actually use in my template (in ternaries). 

I tried to find the settings everywhere but I can't seem to find anything. I even removed and reinstalled the extension but it keeps doing it.

Where is that setting stored and how do I disable it?

**Comment by dtarnawsky** [comment]
Hey @MattOnyx, working on this right now, hopefully fixed today - once complete you'll find a setting in there to toggle on/off but the extension will also only ever add icons and won't remove them (particularly in cases where you use code to determine the icon name).

**Comment by dtarnawsky** [comment]
Hi @MattOnyx,

This is now fixed in v1.94.1. You'll find that the extension wont touch any icons you have already imported because you have them in ternaries, and will only over add Icons if you add them to the template. The feature can also be turned off by going to `Settings` > `Advanced` > `Auto Import Icons` and choosing `no`.

**Comment by MattOnyx** [comment]
Will try this on Monday, thank you for your time!
